services:
  timetracker:
    image: illerin/timetracker:latest
    container_name: timetracker
    ports:
      - "3025:3000"
    volumes:
      - timetracker-data:/data
      
volumes:
  timetracker-data:
